server:
    port: 8080
#文件上传配置
multipart:
    enabled: true
    maxFileSize: 100Mb
    maxRequestSize: 100Mb
    location: ./upload
#spring config
spring:
    profiles:
       active: dev
    freemarker :
        suffix : .ftl
        request-context-attribute : request
        expose-request-attributes : true
    mvc:
        favicon:
            enabled: false
    aop:
      auto: true
# MyBatis
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
    config: classpath:config/mybatis-config.xml
#    dynamic-datasource: true  #启用mybatis动态数据源
hsweb:
    app:
      name: hsweb demo
      version: 1.0
      comment: 演示项目